# Site settings
title: We Create Top!
email: 814084764@qq.com
description: > # this means to ignore newlines until "baseurl:"
  爱钓鱼的程序员
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wecreate.top" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
# twitter:  username
# weibo:    ID
# github:   username
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
